### PR TITLE
Update preflight to v1.11.1

### PR DESCRIPTION
**Pull request by sebrandon1**
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.11.1

### CODE REVIEW

**Comment by sebrandon1** [comment]
@ramperher This new update to preflight v1.11.1 adds a new test which is failing in the DCI run:

```
'actual_result': {'testcase': 'preflight-HasRequiredLabel', 'passed': False}}]"}
```

**Review by rdavid — APPROVED** [review]

**Comment by itroyano** [comment]
The good news is the new test ran :)

**Comment by ramperher** [comment]
> @ramperher This new update to preflight v1.11.1 adds a new test which is failing in the DCI run:
> 
> ```
> 'actual_result': {'testcase': 'preflight-HasRequiredLabel', 'passed': False}}]"}
> ```

I've added an exception for this test in our pipeline, but note we're testing your sample workload in all these jobs, so if this test is failing, this means your workload needs to be updated to pass this test, and also the other one that is failing, which is `preflight-HasUniqueTag`.

**Comment by itroyano** [comment]
cc: @acornett21 @komish
Looks like a test image that doesn't set a "maintainer" level,  sets the name at "Red Hat",  or both.

**Pull request merged**
